name: 同步到 CNB
on:
  workflow_dispatch:
  push:
jobs:
  run:
    name: 同步到 CNB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://cnb.cool/lingyicute/reinstall.git
          GIT_USERNAME: cnb
          GIT_PASSWORD: ${{ secrets.CNB_TOKEN }}
          PUSH_ALL_REFS: false
